import sys,os
import ROOT
from fnmatch import fnmatch
import argparse
import csv

#
class MyColors:
    ''' Simple class to create a sequence of colors from a predefined set
    '''
    def __init__(self,colors=[1,2,4,6,7,8]):
        # init with sorted list of ROOT color codes
        assert colors
        self.colors = colors
        self.idx = None

    def next(self):
        # return next color in sequence
        if self.idx==None:
            self.idx = 0
            return self.colors[self.idx]
        self.idx += 1
        self.idx %= len(self.colors)
        return self.colors[self.idx]

def processPad(pad):
    ''' Retrieve fit results from a single TPad
    '''
    histo = None
    for o in pad.GetListOfPrimitives():
        if o.InheritsFrom(ROOT.TH1.Class()) and o.GetDimension()==1:
            assert histo==None
            histo = o

    result = None
    if histo:
        print(histo.GetName())
        gaus = None
        for f in histo.GetListOfFunctions():
            if f.GetName()=="gaus":
                assert gaus==None
                gaus = f
                n = f.GetNpar()
                assert n==3
                result = [ ]
                for i in range(1,3):
                    result.append((f.GetParameter(i),f.GetParError(i)))
    return result
            
def processFile(rootfile):
    ''' Retrieve fit results from a single root file generated by DrawHits
    '''
    tf = ROOT.TFile(rootfile)
    mainCnv = None
    for k in tf.GetListOfKeys():
        o = tf.Get(k.GetName())
        if o.InheritsFrom(ROOT.TCanvas.Class()):
            assert mainCnv==None
            mainCnv = o
    assert mainCnv

    pads = [ ]
    for p in mainCnv.GetListOfPrimitives():
        if p.InheritsFrom(ROOT.TPad.Class()):
            pads.append(p)
            if len(pads)>=3:
                break
    assert len(pads)==3

    results = [ ]
    for p in pads:
        result = processPad(p)
        results.append(result)

    return results

parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('--zones', '-z', help='zone name(s) (trailing part of input file names, with wildcard)', \
                        type=str, default='*')
parser.add_argument('--csv', help='csv output file', type=str, default=None)
parser.add_argument('--output', '-o', help='output directory for graphic output', type=str, default=None)
parser.add_argument('--formats', help='comma-separated list of extensions for output files', \
                        type=str, default="pdf,png")
parser.add_argument('directories', help='directories with stored canvases in root format', type=str, nargs='+')
args = parser.parse_args()
if args.output!=None:
    assert os.path.isdir(args.output)
zones = [ x.strip() for x in args.zones.split(",") ]


ROOT.gStyle.SetOptStat(0)
allResults = { }
allFnGens = set()
newFnGens = { }
for d in args.directories:
    assert os.path.isdir(d)
    dn = os.path.basename(os.path.normpath(d))
    assert not dn in allResults
    allResults[dn] = { }
    dnResults = allResults[dn]

    fncode = None
    for root,dirs,files in os.walk(d):
        for f in files:
            fname,fext = os.path.splitext(f)
            if fext!=".root":
                continue
            fields = fname.split("_")
            fngen = ( fields[0],"_".join(fields[2:]) )
            if not any([ fnmatch(fngen[1],x) for x in zones ]):
                continue
            if fncode!=None:
                assert fields[1]==fncode
            else:
                fncode = fields[1]
            results = processFile(os.path.join(root,f))
            print(results)
            nNone = sum([ x==None for x in results ])
            assert nNone==0 or nNone==3
            if nNone==0:
                #fngen = "_".join(fields[:1]+fields[2:])
                fngen = ( fields[0],"_".join(fields[2:]) )
                print(fngen)
                allFnGens.add(fngen)
                assert not fngen in dnResults
                dnResults[fngen] = results
#print(allFnGens)
#sys.exit()

mTypes = range(23,26)
parNames = [ 'mean', 'width' ]
dns = sorted(allResults.keys())
nDns = len(dns)

if args.csv!=None:
    with open("tmpFitResults.csv","wt") as csvFile:
        csvWriter = csv.writer(csvFile)

        hdrRow1 = [ 'Canvas' ]
        hdrRow2 = [ '' ]
        hdrRow3 = [ '' ]
        for pn in parNames:
            hdrRow1.append(pn)
            hdrRow1.extend((nDns*len(mTypes)-1)*[''])
            for mtype in mTypes:
                hdrRow2.append("mType "+str(mtype))
                hdrRow2.extend((nDns-1)*[''])
                for dn in dns:
                    hdrRow3.append(dn)
        csvWriter.writerow(hdrRow1)
        csvWriter.writerow(hdrRow2)
        csvWriter.writerow(hdrRow3)

        for fnGen in sorted(allFnGens):
            row = len(hdrRow1)*[ '' ]
            row[0] = "_".join(fnGen)
            idx = 1
            for ipn in range(len(parNames)):
                for im in range(len(mTypes)):
                    for idn,dn in enumerate(dns):
                        dnResults = allResults[dn]
                        if fnGen in dnResults:
                            fnResults = dnResults[fnGen]
                            if fnGen=='cPullXW1_barrel':
                                print(ipn,im,idn,dn)
                                print(" ",fnResults[im][ipn])
                            idx = 1 + idn + im*len(dns) + ipn*len(dns)*len(mTypes)
                            v = fnResults[im][ipn][0]
                            r = "{:4g}".format(v)
                            if "pull" in fnGen.lower():
                                if parNames[ipn]=='mean':
                                    r = '{:7.3f}'.format(v)
                                elif parNames[ipn]=='width':
                                    r = '{:7.3f}'.format(v)
                            if "res" in fnGen.lower():
                                if parNames[ipn]=='mean':
                                    r = '{:7.2f}'.format(10000*v)
                                elif parNames[ipn]=='width':
                                    r = '{:7.2f}'.format(10000*v)
                            #row[idx] = str(fnResults[im][ipn][0])
                            row[idx] = r
            csvWriter.writerow(row)

        csvFile.close()

cnvs = { }
frames = [ ]
legs = [ ]
graphs = { }
fnRoots = set( [ x[0] for x in allFnGens ] )
fnZones = set( [ x[1] for x in allFnGens ] )
for fnRoot in sorted(fnRoots):
    cnvs[fnRoot] = { x:{ } for x in parNames }
    graphs[fnRoot] = { x:{ } for x in parNames }
    for ipn,pn in enumerate(parNames):
        cnv = ROOT.TCanvas(fnRoot+"-"+pn,fnRoot+"-"+pn,600,600)
        cnv.SetBottomMargin(0.15)
        cnvs[fnRoot][pn] = cnv
        graphs[fnRoot][pn] = { }
        for fnZone in fnZones:
            graphs[fnRoot][pn][fnZone] = { }
            for mt in mTypes:
                graphs[fnRoot][pn][fnZone][mt] = { }
        #graphs[fnRoot][pn] = { x:{ } for x in mTypes }
        frames.append(ROOT.TH1F("h"+fnRoot[1:]+"-"+pn,"h"+fnRoot[1:]+"-"+pn,nDns,-0.5,nDns-0.5))
        if pn=='mean':
            #frames.append(cnv.DrawFrame(-0.5,-1,nDns-0.5,1))
            if "pull" in fnRoot.lower():
                frames[-1].GetYaxis().SetTitle('mean (pull)')
            elif "res" in fnRoot.lower():
                frames[-1].GetYaxis().SetTitle('mean (residual) #mm')
        elif pn=='width':
            #frames.append(cnv.DrawFrame(-0.5,0,nDns-0.5,100))
            if "pull" in fnRoot.lower():
                frames[-1].GetYaxis().SetTitle('sigma (pull)')
            elif "res" in fnRoot.lower():
                frames[-1].GetYaxis().SetTitle('sigma (residual) #mm')
        for idn,dn in enumerate(dns):
            frames[-1].GetXaxis().SetBinLabel(idn+1,dn)
        frames[-1].GetXaxis().SetLabelSize(0.05)
        ymin,ymax = 1.e30,-1.e30
        lstyle = MyColors([1,2,3])
        marker = 20
        for iz,fnZone in enumerate(sorted(fnZones)):
            istyle = lstyle.next()
            color = MyColors()
            for im,mt in enumerate(mTypes):
                graph = ROOT.TGraphErrors()
                graph.SetName("g"+fnZone+"-"+pn+"-"+str(mt))
                graph.SetTitle("g"+fnZone+"-"+pn+"-"+str(mt))
                graph.SetLineWidth(2)
                ic = color.next()
                graph.SetLineColor(ic)
                graph.SetLineStyle(istyle)
                graph.SetMarkerStyle(marker)
                marker += 1
                graph.SetMarkerColor(ic)
                graphs[fnRoot][pn][fnZone][mt] = graph
                fnGen = ( fnRoot, fnZone )
                for idn,dn in enumerate(dns):
                    dnResults = allResults[dn]
                    if fnGen in dnResults:
                        fnResults = dnResults[fnGen]
                        v,e = fnResults[im][ipn]
                        if "res" in fnRoot.lower():
                            v *= 10000
                            e *= 10000
                        graph.AddPointError(idn+nDns*iz/50,v,0.,e)
                        ymin = min(ymin,v-e)
                        ymax = max(ymax,v+e)
        if pn=='mean':
            dy = ymax - ymin
            ymin -= dy*0.05
            ymax += dy*0.15
        elif pn=='width':
            ymin = 0.
            ymax *= 1.15
        frames[-1].SetMinimum(ymin)
        frames[-1].SetMaximum(ymax)
        frames[-1].Draw()
        leg = ROOT.TLegend(0.15,0.80,0.90,0.90)
        leg.SetNColumns(4)
        leg.SetBorderSize(0)
        leg.SetFillStyle(0)
        legs.append(leg)
        for fnZone in sorted(fnZones):
            leg.AddEntry("",fnZone,"")
            for mt in mTypes:
                leg.AddEntry(graphs[fnRoot][pn][fnZone][mt],"mType "+str(mt),"LP")
                graphs[fnRoot][pn][fnZone][mt].Draw("PL")
        leg.Draw()
        cnv.Update()
        if args.output!=None:
            for fmt in [ x.strip() for x in args.formats.split(",") ]:
                fnout = os.path.join(args.output,cnv.GetName()+"."+fmt)
                cnv.SaveAs(fnout)
                          

